
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mikltjgbvxrxndtszorb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "your-anon-key-here"; // You'll need to replace this with the anon key from your new project

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
